import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import {
  ClerkProvider,
  useUser,
  SignIn,
  SignedOut,
  SignInButton,
  UserButton,
} from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const { data } = api.posts.getAll.useQuery();

  const user = useUser();

  // console.log(data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <UserButton />}
        </div>
        <div>
          {data?.map((post) => (
            <div key={post.id}>{post.content}</div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;

// export async function getServerSideProps(context) {
//   console.log(context);
//   const response = await fetch(
//     "https://onlinesim.io/api/getNumbersStats.php?apikey=cfdddd7dca0fb1f192caa4e520291944&country=31",
//     {
//       method: "GET",
//     }
//   );
//   const data = await response.json();

//   return {
//     props: data,
//   };
// }
